databases:
  - name: test-url-db
    plan: free
    region: oregon
    databaseName: test_url_db

services:
  # Web Service
  - type: web
    name: test-url
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: pnpm install && pnpm exec nx build test-url
    startCommand: cd $RENDER_ROOT_DIR && node dist/main.js
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000

      - key: DB_HOST
        fromDatabase:
          name: test-url-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: test-url-db
          property: port

      - key: DB_USER
        fromDatabase:
          name: test-url-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: test-url-db
          property: password

      - key: DB_NAME
        fromDatabase:
          name: test-url-db
          property: database

      - key: DB_SSL
        value: true
